language: node_js
node_js:
  - 'stable'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-hm-plugin' ]; then cd .. && eval "mv $currentfolder generator-hm-plugin" && cd generator-hm-plugin; fi
